### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by djaydev** [IvoNet/docker-make#1]
Would it be possible to add image removal of the base image(s)? For example, if I "make projectX" that has "FROM debian:10" in the docker file, can the make program remove the debian;10 image after pushing to docker registry? I'm guessing an additional option like "rmi-base-image" or something. thanks

**Comment by IvoNet** [comment]
added 'rmi-base-images' target to the Makefile. Check it out and give some feedback please.
Oh a star would be nice to :-)

**Comment by IvoNet** [comment]
also added a 'deep-clean' target which will do the clean + 'rmi-base-images'

**Comment by djaydev** [comment]
Thanks for adding it!
I think I maybe missing dependencies, not sure.
Everytime I run it I get the following two lines.
```
Makefile:45: target 'version' given more than once in the same rule
Makefile:48: target 'release-version' given more than once in the same rule
```
Also, for me it stated the images were being removed but it didn't really remove it.
```
Removing all the base (FROM) images used in the projects
alpine
/bin/sh: jq: not found
sh: ==: argument expected
/bin/sh: jq: not found
sh: ==: argument expected
/bin/sh: jq: not found
sh: ==: argument expected
```
That jq not found repeated several times.

I think this last thing is outside of scope, but I was trying to just build one image, then publish-latest just that image but the program would always try to push everything in the folder.  I even tried to specify just the image I wanted pushed:
`make nextcloud-news-updater publish-latest nextcloud-news-updater rmi-base-images`

**Comment by IvoNet** [comment]
Thanks for the comment!
yes jq is needed for parsing json

on a mac `brew install jq` 

Will add this to the README.md.

**Comment by djaydev** [comment]
Adding jq got rid of the errors jq not found, but it doesn't remove the base image alpine:latest. My guess is it's not including the tag, but that's my fault inside the Dockerfile I only specify "alpine" not "alpine:latest".  If the layers are used by other images you can't use "rmi alpine" has to be "rmi alpine:latest" I believe.  
This one maybe a bit advanced for me I'm really just looking to build, push, rmi bases all in one but I should probably just write a simple bash script for that. I appreciate you giving it a try though

**Comment by IvoNet** [comment]
it is never a good idea to use latest (bad practice) in your docker FROM but I will have a look at it.

**Comment by IvoNet** [comment]
added 'latest' as default version if no version is supplied in the FROM.

**Comment by djaydev** [comment]
I think it's mostly working.  The last line it doesn't get the base image name before the ":"

```
bash-5.0# make nextcloud-news-updater publish-latest rmi-base-images  
docker build -t djaydev/nextcloud-news-updater nextcloud-news-updater
Sending build context to Docker daemon  3.072kB
Step 1/4 : FROM alpine
 ---> 961769676411
Step 2/4 : RUN apk add --no-cache python3
 ---> Using cache
 ---> 130a74e0c939
Step 3/4 : RUN pip3 install --no-cache-dir nextcloud_news_updater --install-option="--install-scripts=/usr/bin"
 ---> Using cache
 ---> 6e9efeed6a15
Step 4/4 : CMD nextcloud-news-updater $NEXTCLOUD_URL --user $NEXTCLOUD_USER --password $NEXTCLOUD_TOKEN
 ---> Using cache
 ---> 1446c5b1f056
Successfully built 1446c5b1f056
Successfully tagged djaydev/nextcloud-news-updater:latest
The push refers to repository [docker.io/djaydev/nextcloud-news-updater]
104c7e6be863: Layer already exists
1290ba7fb8b3: Layer already exists
03901b4a2ea8: Layer already exists
latest: digest: sha256:995f8b2dac25c976e9a6751ebbc0458c14e1c376694465480a154e31c6446e05 size: 949
Removing all the base (FROM) images used in the projects
No version fount, assumong latest
:latest
```
